### ISSUE TITLE
US 8: Automatically generate output reports

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/cplus-plugin#43] opened 2023-04-13 14:16 UTC
After running the analysis tool, the user should have an option to generate a report. A QGIS template (qpt), included with the plugin, should be used for the report. In addition to contributing implementation model maps, the report should include the following:
- Overall scenario outcome
- Name
- Description
- Implementation models
- Statistics
- Area of the project (km2?)
- Cost of the implementation models in NVP/ha
- Carbon impact
- Company logo and other contributing organizations

Here is a report example:
![image](https://user-images.githubusercontent.com/79740955/231787481-9b68f20b-aa4a-4d03-9aee-e30014fd3e26.png)

**Comment by Samweli** [comment] 2023-05-19 07:32
Duplicate of https://github.com/kartoza/cplus-plugin/issues/95

**Closed by Samweli** 2023-05-19 07:32 UTC
Labels: Implementation
