### ISSUE TITLE
Create plugin configuration tab in the QGIS options

### ISSUE THREAD

**Issue by amyburness** [kartoza/cplus-plugin#35] opened 2023-04-13 11:57 UTC
Analysis config:
- Organization
- Contact email
- Website
- Custom logo
- Logo preview
- Licence

Download:
- Data location: Location in which default data is stored
- Download data: Open above location?

![image](https://user-images.githubusercontent.com/77841514/231751115-571b0b44-77f1-4848-a9e9-ab81a818e5ba.png)

**Comment by vermeulendivan** [comment] 2023-04-13 14:56
Are these analysis config options optional?
Should a user always provide a default location before using the plugin?

**Comment by vermeulendivan** [comment] 2023-07-07 09:21
@Samweli This is a duplicate of the options, can be closed

**Closed** 2023-07-15 12:13 UTC
Labels: Size: 8, Implementation
