### ISSUE TITLE
Plugin documentation

### ISSUE THREAD

**Issue by vermeulendivan** [kartoza/cplus-plugin#45] opened 2023-04-26 08:11 UTC
Document the features of the plugin and the work which went into the development of the plugin. Provide a proper explanation of the plugin workflow.

- Workflow (QGIS model created from the ArcPy model)
- Functionality of the plugin
- Encountered problems and workarounds
- Changes to the original scope
- etc

**Comment by Samweli** [comment] 2023-05-19 07:39
Duplicate of https://github.com/kartoza/cplus-plugin/issues/50

**Closed by Samweli** 2023-05-19 07:39 UTC
Labels: documentation
